### ISSUE TITLE
Side Navigation Pannel

### ISSUE THREAD

**Issue by naumanshahid007** [naumanshahid007/Acadmy_Management_system#3]
Make the side navigation accordingly:
1. Home
2. Manage Admins
3. System Settings
    * Institute
    * Branches
    * Groups
    * Classes
    * Subjects
4. Teachers
    * Teachers personal info
    * Teacher assign
5. Students
    * Students personal info
    * Student enrollment
6. Fee
    * Fee voucher

**Comment by muhammadsaifrehman** [comment]
Side navigation panel is completed

**Comment by naumanshahid007** [comment]
Good job
